$(document).ready(function(){
  $("#h1").click(function(){
    $("#a1").hide();
  });
  $("#s1").click(function(){
    $("#a1").show();
  });
  $("#h2").click(function(){
    $("#a2").hide();
  });
  $("#s2").click(function(){
    $("#a2").show();
  });
  $("#h3").click(function(){
    $("#a3").hide();
  });
  $("#s3").click(function(){
    $("#a3").show();
  });
  $("#h4").click(function(){
    $("#a4").hide();
  });
  $("#s4").click(function(){
    $("#a4").show();
  });
  $("#h5").click(function(){
    $("#a5").hide();
  });
  $("#s5").click(function(){
    $("#a5").show();
  });
});